name: Sync Template

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  sync-with-template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 1
    - name: Run GitHub File Sync
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        GH_PAT: ${{ secrets.GHCR_TOKEN }}